### PR TITLE
revised report and model after review

### PR DESCRIPTION
**Pull request by Incei**
revised report and model after review

### CODE REVIEW

**Comment by Yuri05** [comment]
@Incei Please also fix spelling (or add to wordlist.txt)
```
Misspelled words:
<htmlcontent> evaluation/Input/Content/References.md: html>body>p
--------------------------------------------------------------------------------
BG
Bayliss
Beaune
Boobis
Carlile
JB
JC
Pelkonen
RJ
ZE
hepatocellularity
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> evaluation/Input/Content/References.md: html>body>p
--------------------------------------------------------------------------------
Ebner
Inoue
Ishiguro
Kawakami
Kishimoto
Liehner
Ohtsuki
Saito
Schaefer
Schwellinger
Terasaki
dmd
glucuronosyltransferases
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md: html>body>p
--------------------------------------------------------------------------------
Polymerase
--------------------------------------------------------------------------------

Misspelled words:
<htmlcontent> evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md: html>body>p
--------------------------------------------------------------------------------
MPPGL
Ohtsuki
--------------------------------------------------------------------------------
```

**Comment by Incei** [comment]
> @Incei Please also fix spelling (or add to wordlist.txt)
> 
> ```
> Misspelled words:
> <htmlcontent> evaluation/Input/Content/References.md: html>body>p
> --------------------------------------------------------------------------------
> BG
> Bayliss
> Beaune
> Boobis
> Carlile
> JB
> JC
> Pelkonen
> RJ
> ZE
> hepatocellularity
> --------------------------------------------------------------------------------
> 
> Misspelled words:
> <htmlcontent> evaluation/Input/Content/References.md: html>body>p
> --------------------------------------------------------------------------------
> Ebner
> Inoue
> Ishiguro
> Kawakami
> Kishimoto
> Liehner
> Ohtsuki
> Saito
> Schaefer
> Schwellinger
> Terasaki
> dmd
> glucuronosyltransferases
> --------------------------------------------------------------------------------
> 
> Misspelled words:
> <htmlcontent> evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md: html>body>p
> --------------------------------------------------------------------------------
> Polymerase
> --------------------------------------------------------------------------------
> 
> Misspelled words:
> <htmlcontent> evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md: html>body>p
> --------------------------------------------------------------------------------
> MPPGL
> Ohtsuki
> --------------------------------------------------------------------------------
> ```

These are all new references, can be added to wordlist

**Comment by Yuri05** [comment]
@Incei From my point of view all fine here. Should we merge? Or are your waiting for the final feedback regarding the report from others?

**Comment by Incei** [comment]
> @Incei From my point of view all fine here. Should we merge? Or are your waiting for the final feedback regarding the report from others?

I am awaiting a final review-feedback from @sfrechen :)

**Comment by Yuri05** [comment]
ok

**Comment by Yuri05** [comment]
@sfrechen @Incei any updates?

**Comment by Incei** [comment]
@Yuri05  Updates  will follow soon.

**Comment by Yuri05** [comment]
>Updates will follow soon.

sooner than my retirement? 😉

**Comment by Yuri05** [comment]
@Incei This PR can be closed now in favor of the latest one?

**Pull request closed without merging**
